#!/bin/bash
# usage: usblogin create path-to-device username / usblogin verify path-to-device username / usblogin init
set -e

[ "$1" == "init" ] && mkdir -p /var/lib/usblogin-keys
[ "$1" == "create" ] && echo USBLOGINKEY$(dd if=/dev/urandom of=/dev/stdout count=16384) > $2 && sha512sum $2 | cut -d " " -f 1 > /var/lib/usblogin-keys/$3
[ "$1" == "verify" ] && [ "$(sha512sum $2 | cut -d ' ' -f 1)" == "$(cat /var/lib/usblogin-keys/$3)" ] || exit 1
